USE [Writings]
GO

INSERT INTO [dbo].[Story]
           ([Title]
           ,[UserName]
           ,[TagName]
           ,[Description]
           ,[IsAnonymous]
           ,[CreatedOn]
           )
   values(
'View at the surface',	'Maha',	'#life',
'Am talking about people here... Look at the people only at the surface.       If get attached to them or move closer to them... there comes the problems   Lots of expectations, difference in opinions, frictions, fighting, dealing with egos etc.      For example, if u go to a beach and looking from the surface..   we can see pleasant waves, fresh air, blue sky and a beautiful view.    You can feel the water when waves touching your feet when u are at the surface.   But if u liked that and went deeper into the sea...    Salt water, no air, suffocation, sharks and snakes, under water pressure etc... a life threat      One more example, if we look at the moon at night from earth..   We can feel cool climate, calm and charming moon light   But what if we land on the moon..   No gravity, no atmosphere, no oxygen, no water, it''s even hard to walk.      Similarly, when we see at a person.. he/she may be charming, helpful, generous, smart, funny, etc.   But if we get too much attached to him/her... things may reverse. So don’t get attached.      This don’t mean that don’t mingle with anyone and go to Island and live there.. What I mean is that if you like or love or living with a person, see him only from the surface don’t go deep.      As *Gautham said.. "Attachment leads to suffering"      So, don’t get too close or too attached to anyone including your family members, friends, relatives and others.   Stay busy in your own way and create your own big world!!!      What if someone attached to you................  that''s a different story!! 😁            _____________________________________________________________________________________Note: *Gautham is not my friend. Gautham means Gautama Buddha...😉' ,
0,	GETUTCDATE()),
('Simple Ways to Be Happier',	'Happie',	'#happy',
'1. Meaningful relationships  For many, "meaningful relationship" means marriage and family. Many unmarried people enjoy happy, meaningful, satisfying lives, though. The fact that they don''t marry doesn''t prevent them from creating meaningful bonds with friends or with communities of like-minded people.  2. Meaningful work  Everyone needs work, whether you receive pay for it or not. Everyone needs to feel they contribute something to the world, that the world needs them. It doesn''t matter if your work is president of the country or garbage collector -- do something cheerfully and well, and know if you''re not doing it tomorrow, someone will miss you and what you did.  3. Serving others  Notice others just as you want people to notice that you are here, and do what you can to help others live meaningful lives. Serving others means different things, depending on what other people need. Something as small as a smile when you pass a person can make their day. Pay attention to what others need.  4. Maintaining a positive outlook  Studies show that religious people are generally happy. All mainstream religions train your brain for a positive outlook. You can do that for yourself as well.  5. Punctuating life  Sameness becomes monotonous, without forward momentum. Punctuate your life with occasions and rituals, bringing heightened awareness to certain times, places and activities.  6. Feeling gratitude in the moment  While remembering the past and planning for the future provide continuity in life, it''s important to balance that with your presence in the moment and to experience and express gratitude in the moment.  7. Connecting  Throughout history, people lived rich and satisfying lives in all kinds of circumstances. Wealth is not a requirement. Meaning-filled connection is. Connecting to other people, to the environment that sustains us, to our communities, to our ethnic and national histories and to transcendence brings us a sense of our place in eternity. Maybe we''re small, but we''re part of something very big, and that gives us a different perspective on change and loss, even on suffering.',
1,	GETUTCDATE()),
('The Second Arrow',	'Unknown', '#buddha #lifelesson',
'The Buddha once asked a student,     “If a person is struck by an arrow, is it painful?” The student replied , “It is.”  The Buddha then asked,     “If the person is struck by a second arrow, is that even more painful?” The student replied again, “It is.”  The Buddha then explained,     “In life, we cannot always control the first arrow. However, the second arrow is our reaction to the first. And with this second arrow comes the possibility of choice.  While we can’t control our outside environment, we can, with practice, change this pattern of shooting a second arrow after the first. There are two very effective exercises which you can practice in order to circumvent this all-too-human response to life – firstly, noticing the pattern of the second arrow; secondly, practicing kindness to yourself when you see it.',	
1,	GETUTCDATE())

GO


